CREATE OR REPLACE TRIGGER check_min_stock
BEFORE INSERT OR UPDATE OF PRODUCTQTY ON WAREHOUSE
FOR EACH ROW
DECLARE
    min_stock PRODUCT.MINSTOCKQUANTITY%TYPE;
BEGIN
    SELECT MINSTOCKQUANTITY INTO min_stock FROM PRODUCT WHERE PRODUCTID = :NEW.PRODUCTID;
    IF :NEW.PRODUCTQTY <= min_stock THEN
        :NEW.PRODUCTQTY := 50;
    END IF;
END;
/
