SET
    SERVEROUTPUT ON;

DECLARE V_USER VARCHAR(100);

BEGIN
SELECT
    USERNAME INTO V_USER
FROM
    ALL_USERS
WHERE
    USERNAME = 'INVENTORYADMIN';

DBMS_OUTPUT.PUT_LINE('USER: INVENTORYADMIN already exists');

EXCEPTION
WHEN NO_DATA_FOUND THEN EXECUTE IMMEDIATE 'CREATE USER INVENTORYADMIN IDENTIFIED BY Admin1234567';

EXECUTE IMMEDIATE '
    GRANT 
        CONNECT,
        RESOURCE, 
        CREATE USER, 
        DROP USER,
        CREATE ANY VIEW,
        UNLIMITED TABLESPACE
    TO 
        INVENTORYADMIN 
    WITH 
        ADMIN OPTION';

DBMS_OUTPUT.PUT_LINE ('INVENTORYADMIN created successfully');

END;

/